#!/bin/sh
# Script to launch trayer in the correct position next to xmobar.
# Author: Vic Fryzel
# http://github.com/vicfryzel/xmonad-config

trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --widthtype pixel --width 164 --transparent true --alpha 0 --tint 0x000000 --height 32
